# copyright: sktime developers, BSD-3-Clause License (see LICENSE file)
"""Tests for BaseCausalDiscoverer API points."""

__author__ = ["sktime developers"]

import numpy as np
import pandas as pd

from sktime.tests.test_all_estimators import BaseFixtureGenerator, QuickTester


class CausalDiscovererFixtureGenerator(BaseFixtureGenerator):
    """Fixture generator for causal discovery estimators.

    Fixtures parameterized
    ----------------------
    estimator_class: estimator inheriting from BaseObject
        ranges over estimator classes not excluded by EXCLUDE_ESTIMATORS, EXCLUDED_TESTS
    estimator_instance: instance of estimator inheriting from BaseObject
        ranges over estimator classes not excluded by EXCLUDE_ESTIMATORS, EXCLUDED_TESTS
        instances are generated by create_test_instance class method
    scenario: instance of TestScenario
        ranges over all scenarios returned by retrieve_scenarios
    """

    estimator_type_filter = "causal_discoverer"


class TestAllCausalDiscoverers(CausalDiscovererFixtureGenerator, QuickTester):
    """Module level tests for all sktime causal discovery estimators."""

    def test_graph_output_contract(self, estimator_instance):
        """Test that graph outputs follow BaseCausalDiscoverer contract."""
        rng = np.random.default_rng(42)
        X = pd.DataFrame(rng.normal(size=(120, 4)), columns=["x0", "x1", "x2", "x3"])

        estimator_instance.fit(X)

        adj = estimator_instance.get_adjacency_matrix()
        graph = estimator_instance.get_graph()
        edges = estimator_instance.get_edge_list()

        assert isinstance(adj, np.ndarray)
        assert isinstance(graph, dict)
        assert isinstance(edges, list)
        assert set(graph.keys()) == {
            "adjacency_matrix",
            "variable_names",
            "graph_type",
            "edge_encoding",
            "p_values",
            "link_coefficients",
        }

        is_ts = estimator_instance.get_tag("capability:time_series")
        if is_ts:
            assert adj.ndim == 3
            assert adj.shape[0] == adj.shape[1] == len(graph["variable_names"])
        else:
            assert adj.ndim == 2
            assert adj.shape[0] == adj.shape[1] == len(graph["variable_names"])
